In [340]:
import pandas as pd

In [341]:
df=pd.read_csv("Data.csv")
df.head(10)

   Id   age Department   Salary    JoinDate
0   1  25.0         Hr  45000.0  2022-01-10
1   2   NaN         it  60000.0   2021-11-5
2   3  32.0     fiance      NaN  2020-06-18
3   4  28.0        NaN  52000.0         NaN
4   5  45.0         Hr  70000.0  2019-03-22
5   6  30.0         it      NaN  2022-08-14
6   7   NaN  marketing  48000.0  2021-02-14
7   8  38.0     fiance  65000.0         NaN
8   9  26.0        NaN  50000.0  2023-01-09
9  10  41.0  marketing      NaN  2020-12-30

In [342]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          10 non-null     int64
 1   age         8 non-null      float64
 2   Department  8 non-null      object
 3   Salary      7 non-null      float64
 4   JoinDate    8 non-null      object
dtypes: float64(2), int64(1), object(2)
memory usage: 532.0+ bytes

In [343]:
df.isna().sum()

Id            0
age           2
Department    2
Salary        3
JoinDate      2
dtype: int64

In [344]:
new_df=df.dropna()
new_df.head()

   Id   age Department   Salary    JoinDate
0   1  25.0         Hr  45000.0  2022-01-10
4   5  45.0         Hr  70000.0  2019-03-22

In [345]:
newww_df=df.dropna(axis=1)
newww_df.head()

   Id
0   1
1   2
2   3
3   4
4   5

In [346]:
df_filled=df.fillna(0)
df_filled

   Id   age Department   Salary    JoinDate
0   1  25.0         Hr  45000.0  2022-01-10
1   2   0.0         it  60000.0   2021-11-5
2   3  32.0     fiance      0.0  2020-06-18
3   4  28.0          0  52000.0           0
4   5  45.0         Hr  70000.0  2019-03-22
5   6  30.0         it      0.0  2022-08-14
6   7   0.0  marketing  48000.0  2021-02-14
7   8  38.0     fiance  65000.0           0
8   9  26.0          0  50000.0  2023-01-09
9  10  41.0  marketing      0.0  2020-12-30

In [347]:
df['age']=df['age'].fillna(round(df['age'].mean()))

In [348]:
df['Department']=df['Department'].ffill()
df.head(10)

   Id   age Department   Salary    JoinDate
0   1  25.0         Hr  45000.0  2022-01-10
1   2  33.0         it  60000.0   2021-11-5
2   3  32.0     fiance      NaN  2020-06-18
3   4  28.0     fiance  52000.0         NaN
4   5  45.0         Hr  70000.0  2019-03-22
5   6  30.0         it      NaN  2022-08-14
6   7  33.0  marketing  48000.0  2021-02-14
7   8  38.0     fiance  65000.0         NaN
8   9  26.0     fiance  50000.0  2023-01-09
9  10  41.0  marketing      NaN  2020-12-30

In [349]:
df['Salary']=df['Salary'].fillna(round(df['Salary'].mean(),2))

In [350]:
df['Salary'].round(2)
df.head()

   Id   age Department    Salary    JoinDate
0   1  25.0         Hr  45000.00  2022-01-10
1   2  33.0         it  60000.00   2021-11-5
2   3  32.0     fiance  55714.29  2020-06-18
3   4  28.0     fiance  52000.00         NaN
4   5  45.0         Hr  70000.00  2019-03-22

In [351]:
df['JoinDate']=df['JoinDate'].ffill()

In [352]:
df.head()

   Id   age Department    Salary    JoinDate
0   1  25.0         Hr  45000.00  2022-01-10
1   2  33.0         it  60000.00   2021-11-5
2   3  32.0     fiance  55714.29  2020-06-18
3   4  28.0     fiance  52000.00  2020-06-18
4   5  45.0         Hr  70000.00  2019-03-22

In [353]:
df['JoinDate']=pd.to_datetime(df['JoinDate'])

In [354]:
df.dtypes

Id                     int64
age                  float64
Department            object
Salary               float64
JoinDate      datetime64[ns]
dtype: object

In [355]:
df['Year']=df['JoinDate'].dt.year
df['month'] = df['JoinDate'].dt.month
df['day_name'] = df['JoinDate'].dt.day_name()

In [356]:
df.head(10  )

   Id   age Department    Salary   JoinDate  Year  month   day_name
0   1  25.0         Hr  45000.00 2022-01-10  2022      1     Monday
1   2  33.0         it  60000.00 2021-11-05  2021     11     Friday
2   3  32.0     fiance  55714.29 2020-06-18  2020      6   Thursday
3   4  28.0     fiance  52000.00 2020-06-18  2020      6   Thursday
4   5  45.0         Hr  70000.00 2019-03-22  2019      3     Friday
5   6  30.0         it  55714.29 2022-08-14  2022      8     Sunday
6   7  33.0  marketing  48000.00 2021-02-14  2021      2     Sunday
7   8  38.0     fiance  65000.00 2021-02-14  2021      2     Sunday
8   9  26.0     fiance  50000.00 2023-01-09  2023      1     Monday
9  10  41.0  marketing  55714.29 2020-12-30  2020     12  Wednesday

In [357]:
df=df.set_index('JoinDate')

In [358]:
df.loc['2020-06-18']

            Id   age Department    Salary  Year  month  day_name
JoinDate
2020-06-18   3  32.0     fiance  55714.29  2020      6  Thursday
2020-06-18   4  28.0     fiance  52000.00  2020      6  Thursday

In [359]:
df['Department']=df['Department'].astype('category')
df.head()

            Id   age Department    Salary  Year  month  day_name
JoinDate
2022-01-10   1  25.0         Hr  45000.00  2022      1    Monday
2021-11-05   2  33.0         it  60000.00  2021     11    Friday
2020-06-18   3  32.0     fiance  55714.29  2020      6  Thursday
2020-06-18   4  28.0     fiance  52000.00  2020      6  Thursday
2019-03-22   5  45.0         Hr  70000.00  2019      3    Friday

In [360]:
df.dtypes

Id               int64
age            float64
Department    category
Salary         float64
Year             int32
month            int32
day_name        object
dtype: object

In [361]:
df['Dept_code']=df['Department'].cat.codes

In [362]:
df.head()

            Id   age Department    Salary  Year  month  day_name  Dept_code
JoinDate
2022-01-10   1  25.0         Hr  45000.00  2022      1    Monday          0
2021-11-05   2  33.0         it  60000.00  2021     11    Friday          2
2020-06-18   3  32.0     fiance  55714.29  2020      6  Thursday          1
2020-06-18   4  28.0     fiance  52000.00  2020      6  Thursday          1
2019-03-22   5  45.0         Hr  70000.00  2019      3    Friday          0

In [363]:
df.head(10
        )

            Id   age Department    Salary  Year  month   day_name  Dept_code
JoinDate
2022-01-10   1  25.0         Hr  45000.00  2022      1     Monday          0
2021-11-05   2  33.0         it  60000.00  2021     11     Friday          2
2020-06-18   3  32.0     fiance  55714.29  2020      6   Thursday          1
2020-06-18   4  28.0     fiance  52000.00  2020      6   Thursday          1
2019-03-22   5  45.0         Hr  70000.00  2019      3     Friday          0
2022-08-14   6  30.0         it  55714.29  2022      8     Sunday          2
2021-02-14   7  33.0  marketing  48000.00  2021      2     Sunday          3
2021-02-14   8  38.0     fiance  65000.00  2021      2     Sunday          1
2023-01-09   9  26.0     fiance  50000.00  2023      1     Monday          1
2020-12-30  10  41.0  marketing  55714.29  2020     12  Wednesday          3

In [364]:
df['Level']=['junior','Senior','junior','Senior','junior','Senior','junior','Senior','junior','Senior']

In [365]:
df=df.reset_index()

In [366]:
df.head()

,JoinDate,Id,age,Department,Salary,Year,month,day_name,Dept_code,Level
0,2022-01-10,1,25.0,Hr,45000.00,2022,1,Monday,0,junior
1,2021-11-05,2,33.0,it,60000.00,2021,11,Friday,2,Senior
2,2020-06-18,3,32.0,fiance,55714.29,2020,6,Thursday,1,junior
3,2020-06-18,4,28.0,fiance,52000.00,2020,6,Thursday,1,Senior
4,2019-03-22,5,45.0,Hr,70000.00,2019,3,Friday,0,junior

In [367]:
df['Level']=df['Level'].astype('category')

In [368]:
df.head()

,JoinDate,Id,age,Department,Salary,Year,month,day_name,Dept_code,Level
0,2022-01-10,1,25.0,Hr,45000.00,2022,1,Monday,0,junior
1,2021-11-05,2,33.0,it,60000.00,2021,11,Friday,2,Senior
2,2020-06-18,3,32.0,fiance,55714.29,2020,6,Thursday,1,junior
3,2020-06-18,4,28.0,fiance,52000.00,2020,6,Thursday,1,Senior
4,2019-03-22,5,45.0,Hr,70000.00,2019,3,Friday,0,junior

In [369]:
print(df['Level'].cat.categories)

Index(['Senior', 'junior'], dtype='object')

In [370]:
df['Level'] = df['Level'].str.lower().astype('category')
df['Level'] = df['Level'].cat.rename_categories({
    'junior': 'jr',
    'senior': 'sr'
})

In [371]:
df.head()

,JoinDate,Id,age,Department,Salary,Year,month,day_name,Dept_code,Level
0,2022-01-10,1,25.0,Hr,45000.00,2022,1,Monday,0,jr
1,2021-11-05,2,33.0,it,60000.00,2021,11,Friday,2,sr
2,2020-06-18,3,32.0,fiance,55714.29,2020,6,Thursday,1,jr
3,2020-06-18,4,28.0,fiance,52000.00,2020,6,Thursday,1,sr
4,2019-03-22,5,45.0,Hr,70000.00,2019,3,Friday,0,jr